version: '3.8'

services:
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - 5432:5432
  tests:
    build:
      context: .
      dockerfile: tests.Dockerfile
    command: sh -c "python /aiohttp-task_tests/migrations/migrate.py && python -m unittest discover -s /aiohttp-task_tests/tests"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/aiohttp-task_tests

volumes:
  postgres_data:
